---
name: Auto - Verify & plan sandbox environment
on:
  workflow_dispatch:
  push:
    branches: [sandbox-*]
concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: false
jobs:
  terraform_verify:
    environment: ${{ github.ref_name }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_azure_blobstore_opendata_sas_token: ${{ secrets.AZURE_BLOBSTORE_OPENDATA_SAS_TOKEN }}
      TF_VAR_azure_blobstore_internal_public_data_sas_token: ${{ secrets.AZURE_BLOBSTORE_INTERNAL_PUBLIC_DATA_SAS_TOKEN }}
      TF_VAR_azure_datasync_agent_activation_key_uswest2: ${{ secrets.AZURE_DATASYNC_AGENT_ACTIVATION_KEY_USWEST2 }}
      TF_VAR_azure_datasync_agent_activation_key_useast1: ${{ secrets.AZURE_DATASYNC_AGENT_ACTIVATION_KEY_USEAST1 }}
    runs-on: ubuntu-latest
    name: Auto Verify & plan terraform code for sandbox environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform format check
        run: terraform fmt -check -diff -recursive
      - name: Initialize Terraform
        run: terraform init -backend-config="./${{ github.ref_name }}.config"
      - name: Run Terraform Plan
        run: |-
          if [ -e ./scripts/terraform_plan_${{ github.ref_name }}.sh ]
          then
            ./scripts/terraform_plan_${{ github.ref_name }}.sh
          else
            terraform plan -input=false -var-file="${{ github.ref_name }}.tfvars" -out plan.tfplan >/dev/null && terraform show plan.tfplan
          fi
