name: Auto - Verify & plan branch environment
on:
  workflow_dispatch:
  pull_request:
    branches:
      - staging

concurrency:
  group: terraform-${{ github.base_ref }}

permissions:
  contents: read
  packages: read
  pull-requests: write

jobs:

  terraform_verify:
    environment: ${{ github.base_ref }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_ec_apikey: ${{ secrets.ELASTIC_CLOUD_API_KEY }} # nexus uses ELASTIC CLOUD
      TF_VAR_nise_dockerhub_password: ${{ secrets.NISE_DOCKERHUB_PASS }}

    runs-on: ubuntu-latest
    name: Auto Verify & plan terraform code for branch environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          output_format: github_failed_only
          output_file_path: checkov_issues
          quiet: true # display only failed checks
          download_external_modules: true

      - name: Comment with checkov results
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: checkov_issues/results_github_failed_only.md
          comment-tag: checkov # update existing comment instead of adding a new one on every run
        if: failure()

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform format check
        run: terraform fmt -check -diff -recursive

      - name: Initialize Terraform
        run: terraform init -backend-config="./${{ github.base_ref }}.config"

      - name: Run Terraform Plan
        run: |
          terraform plan -var-file="${{ github.base_ref }}.tfvars" -out plan.tfplan >/dev/null && terraform show plan.tfplan
