name: Auto - Apply changes on Merge to staging

env:
  AWS_ROLE_ARN_STAGING: arn:aws:iam::992382665735:role/GithubTerraformDeploy

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]
    branches:
      - staging

concurrency:
  group: terraform-staging-deploy
  cancel-in-progress: false

jobs:
  terraform_apply:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    environment: ${{ github.base_ref }}
    permissions:
      id-token: write
      contents: read
    env:
      TF_VAR_azure_blobstore_opendata_sas_token: ${{ secrets.AZURE_BLOBSTORE_OPENDATA_SAS_TOKEN }}
      TF_VAR_azure_blobstore_internal_public_data_sas_token: ${{ secrets.AZURE_BLOBSTORE_INTERNAL_PUBLIC_DATA_SAS_TOKEN }}
      TF_VAR_azure_datasync_agent_activation_key_uswest2: ${{ secrets.AZURE_DATASYNC_AGENT_ACTIVATION_KEY_USWEST2 }}
      TF_VAR_azure_datasync_agent_activation_key_useast1: ${{ secrets.AZURE_DATASYNC_AGENT_ACTIVATION_KEY_USEAST1 }}

    runs-on: ubuntu-latest
    name: Auto Apply terraform code to staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN_STAGING }}
          aws-region: us-east-1

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Initialize Terraform
        run: terraform init -backend-config="./${{ github.base_ref }}.config"

      - name: Run Terraform Apply
        run: |
          terraform apply -auto-approve -var-file="${{ github.ref_name }}.tfvars"
