name: Manual - Apply changes

env:
  AWS_ROLE_ARN_STAGING: arn:aws:iam::992382665735:role/GithubTerraformDeploy
  AWS_ROLE_ARN_PRODUCTION: arn:aws:iam::671250183987:role/GithubTerraformDeploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Which environment to deploy to
        required: true
        default: staging
        options:
          - staging
          - production

concurrency:
  group: terraform-${{ inputs.environment }}
  cancel-in-progress: false

jobs:
  terraform_deployment:
    environment: ${{ inputs.environment }} # secrets are set per environment https://github.com/openbraininstitute/aws-terraform-deployment/settings/environments
    permissions:
      id-token: write
      contents: read
    env:
      TF_VAR_azure_blobstore_opendata_sas_token: ${{ secrets.AZURE_BLOBSTORE_OPENDATA_SAS_TOKEN }}
      TF_VAR_azure_blobstore_internal_public_data_sas_token: ${{ secrets.AZURE_BLOBSTORE_INTERNAL_PUBLIC_DATA_SAS_TOKEN }}
      TF_VAR_azure_datasync_agent_activation_key_uswest2: ${{ secrets.AZURE_DATASYNC_AGENT_ACTIVATION_KEY_USWEST2 }}
      TF_VAR_azure_datasync_agent_activation_key_useast1: ${{ secrets.AZURE_DATASYNC_AGENT_ACTIVATION_KEY_USEAST1 }}

    runs-on: ubuntu-latest
    name: Manual terraform apply
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.environment == 'production' && env.AWS_ROLE_ARN_PRODUCTION || env.AWS_ROLE_ARN_STAGING }}
          aws-region: us-east-1

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform format check
        run: terraform fmt -check -diff -recursive

      - name: Initialize Terraform
        run: terraform init -backend-config="./${{ inputs.environment }}.config"

      - name: Run Terraform Plan
        run: |
          terraform plan -input=false -var-file="${{ inputs.environment }}.tfvars" -out plan.tfplan >/dev/null && terraform show plan.tfplan

      - name: Run Terraform Apply
        run: |
          terraform apply -auto-approve -var-file="${{ inputs.environment }}.tfvars"
