name: Terraform apply
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'environment name'
        required: true

jobs:
  terraform_apply:
    environment: ${{ inputs.environment }} # secrets are set per environment https://github.com/openbraininstitute/aws-terraform-deployment/settings/environments
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_ec_apikey: ${{ secrets.ELASTIC_CLOUD_API_KEY }} # nexus uses ELASTIC CLOUD
      TF_VAR_nise_dockerhub_password: ${{ secrets.NISE_DOCKERHUB_PASS }}

    runs-on: ubuntu-latest
    name: Run terraform verify
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform format check
        run: terraform fmt -check -diff -recursive

      - name: Initialize Terraform
        run: terraform init -backend-config="./${{ inputs.environment }}.config"

      - name: Run Terraform Plan
        run: |
          terraform plan -var-file="${{ inputs.environment }}.tfvars"

      - name: Run Terraform Apply
        run: |
          terraform apply -var-file="${{ inputs.environment }}.tfvars"
