name: Terraform verify
on:
  pull_request:
    branches:
      - production
      - staging

jobs:
  terraform_verify:
    environment: ${{ github.base_ref }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_ec_apikey: ${{ secrets.ELASTIC_CLOUD_API_KEY }} # nexus uses ELASTIC CLOUD
      TF_VAR_nise_dockerhub_password: ${{ secrets.NISE_DOCKERHUB_PASS }}

    runs-on: ubuntu-latest
    name: Verify & plan terraform code
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform format check
        run: terraform fmt -check -diff -recursive

      - name: Initialize Terraform
        run: terraform init -backend-config="./${{ github.base_ref }}.config"

      - name: Run Terraform Plan
        run: |
          terraform plan -var-file="${{ github.base_ref }}.tfvars"
